---

- hosts: mdk
  vars:
    letsencrypt_email: julien@palard.fr
  tasks:
    - name: Setup certificate watcher
      include_role: name=certificate_watcher
      tags: always
      vars:
        owner: certificate-watcher
        dest: 'irc://irc.libera.chat/#mdk'
        prefix: "mdk:"
        domains: |
          # meltygroup
          pypi.meltylab.fr
          gitlab.eeple.fr

          melty.fr
          www.melty.fr
          www.melty.fr@cdn-onl1.meltygroup.com
          www.melty.fr@cdn-onl2.meltygroup.com
          www.melty.fr@cdn-onl3.meltygroup.com
          www.melty.fr@cdn-ovh1.meltygroup.com
          www.melty.fr@cdn-ovh2.meltygroup.com

          media.melty.fr
          media.melty.fr@cdn-onl1.meltygroup.com
          media.melty.fr@cdn-onl2.meltygroup.com
          media.melty.fr@cdn-onl3.meltygroup.com
          media.melty.fr@cdn-ovh1.meltygroup.com
          media.melty.fr@cdn-ovh2.meltygroup.com
          media.melty.fr@mediamelty.cdnbox.meltygroup.com

          meltygroup.com
          www.meltygroup.com
          media.meltygroup.com

          peaches.fr
          www.peaches.fr
          media.peaches.fr

          trendy.letudiant.fr

          # AFPy
          afpy.org
          bbb.afpy.org
          dl.afpy.org
          logs.afpy.org
          discuss.afpy.org
          mail.afpy.org:993

          fr.pycon.org
          pycon.org

          2010.pycon.fr
          2011.pycon.fr
          2012.pycon.fr
          2016.pycon.fr
          autoconfig.pycon.fr
          cfp-2018.pycon.fr
          cfp-2019.pycon.fr
          cfp-2020.pycon.fr
          cfp.pycon.fr
          paullaroid.pycon.fr
          pycon.fr
          video-2015.pycon.fr
          video.pycon.fr
          www.pycon.fr

          # Python
          bugs.python.org
          mail.python.org
          devguide.python.org
          docs.python.org
          hg.python.org
          legacy.python.org
          packaging.python.org
          pygame.org
          pypi.org
          python.org
          speed.python.org
          wiki.python.org
          www.python.org

          # Hackinscience
          hackinscience.org
          www.hackinscience.org

          # Perso
          julien.palard.fr
          le-poitevin.fr
          mdk.fr
          wyz.fr
          palard.fr
          sizeof.fr
          irc.mdk.fr
          www.mdk.fr
          www.palard.fr
          www.sizeof.fr

          # Friends
          mastodon.etalab.gouv.fr
          protonmail.com
          makina-corpus.com
          humancoders.com
          fr.wikipedia.org
          mamot.fr
          framagenda.org
          framapad.org
          framinetest.org
          framanotes.org
          framasoft.org
          intranetv2.supinternet.fr
          supinternet.fr
          www.epitech.eu
