---

- hosts: mdk
  vars:
    letsencrypt_email: julien@palard.fr
  tasks:
    - name: Setup certificate watcher
      include_role: name=certificate_watcher
      tags: always
      vars:
        owner: certificate-watcher
        dest: mdk
        prefix: "mdk:"
        domains: |
          # meltygroup
          pypi.meltylab.fr
          gitlab.eeple.fr
          media.melty.fr
          melty.es
          melty.fr
          melty.it
          meltygroup.com
          shoko.fr

          # AFPy
          afpy.org
          bbb.afpy.org
          dl.afpy.org
          discuss.afpy.org
          fr.pycon.org
          pycon.fr
          pycon.org
          mail.afpy.org:993

          # Python
          bugs.python.org
          mail.python.org
          devguide.python.org
          docs.python.org
          hg.python.org
          legacy.python.org
          packaging.python.org
          pygame.org
          pypi.org
          python.org
          speed.python.org
          wiki.python.org
          www.python.org

          # Hackinscience
          hackinscience.org
          www.hackinscience.org

          # Perso
          julien.palard.fr
          le-poitevin.fr
          mdk.fr
          wyz.fr
          palard.fr
          sizeof.fr
          irc.mdk.fr
          www.mdk.fr
          www.palard.fr
          www.sizeof.fr

          # Friends
          mastodon.etalab.gouv.fr
          protonmail.com
          makina-corpus.com
          fr.wikipedia.org
          mamot.fr
          framagenda.org
          framapad.org
          framinetest.org
          framanotes.org
          framasoft.org
          intranetv2.supinternet.fr
          supinternet.fr
