---

- hosts: mdk
  vars:
    letsencrypt_email: julien@palard.fr
  tasks:
    - name: Setup certificate watcher
      include_role: name=certificate_watcher
      tags: always
      vars:
        owner: certificate-watcher
        dest: mdk
        prefix: "mdk:"
        domains: |
          # meltygroup
          pypi.meltylab.fr
          admin-framework.staging.meltylab.fr
          admin-meltyfr.staging.meltylab.fr
          ads.meltygroup.com
          api-meltyfr.staging.meltylab.fr
          boost.staging.meltylab.fr
          doc-api-sephora.staging.meltylab.fr
          gitlab.eeple.fr
          media.melty.fr
          melty-instant-article.staging.meltylab.fr
          melty.es
          melty.fr
          melty.it
          meltyfr-amp.staging.meltylab.fr
          meltygroup-amp.staging.meltylab.fr
          meltygroup.com
          meltygroup.staging.meltylab.fr
          meltylab.fr
          sephora.staging.meltylab.fr
          shoko-amp.staging.meltylab.fr
          shoko.fr
          ssr.staging.meltylab.fr
          tyramisu.fr

          # AFPy
          afpy.org
          fr.pycon.org
          pycon.fr
          pycon.org

          # Python
          bugs.python.org
          devguide.python.org
          docs.python.org
          hg.python.org
          legacy.python.org
          packaging.python.org
          pygame.org
          pypi.org
          python.org
          speed.python.org
          wiki.python.org
          www.python.org

          # Hackinscience
          hackinscience.org
          www.hackinscience.org

          # Perso
          julien.palard.fr
          le-poitevin.fr
          mdk.fr
          wyz.fr
          palard.fr
          sizeof.fr
          www.mdk.fr
          www.palard.fr
          www.sizeof.fr

          # Friends
          mastodon.etalab.gouv.fr
          protonmail.com
          makina-corpus.com
          fr.wikipedia.org
          mamot.fr
          framagenda.org
          framapad.org
          framinetest.org
          framanotes.org
          framasoft.org
          intranetv2.supinternet.fr
          supinternet.fr
