---

- hosts: mdk
  vars:
    letsencrypt_email: julien@palard.fr
  tasks:
    - name: Configure hostname
      hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Configure FQDN
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: "127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }} localhost"
        owner: root
        group: root
        mode: 0644

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Configure fail2ban for nginx
      copy:
        content: |
          [nginx-botsearch]
          enabled  = true
          port     = http,https
          logpath  = %(nginx_error_log)s
          maxretry = 2
        dest: /etc/fail2ban/jail.d/nginx.conf
        mode: 0x644
      notify: reload fail2ban

    - name: Configure fail2ban bantime
      copy:
        content: |
          [DEFAULT]
          bantime  = 30d
        dest: /etc/fail2ban/jail.d/mdk-bantime.conf
        mode: 0x644
      notify: reload fail2ban

    - name: Setup nftables
      include_role: name=nftables
      tags: always
      vars:
        nftables_conf: |
            #!/usr/sbin/nft -f

            flush ruleset

            table inet filter {
                chain input {
                    type filter hook input priority 0;
                    iif lo accept
                    ct state established,related accept
                    tcp dport { ssh, http, https, 5201 } ct state new accept
                    ip protocol icmp icmp type { destination-unreachable, echo-reply, echo-request, source-quench, time-exceeded } accept
                    counter drop
                }
            }

    - name: Setup letsencrypt
      include_role: name=julienpalard.nginx_letsencrypt
      tags: always
      vars:
        letsencrypt_certificates:
          - [irc.mdk.fr]
          - [tuw.fr]

    - name: Exim4
      include_role: name=tschifftner.exim4_sendonly

  handlers:
    - name: reload fail2ban
      service: name=fail2ban state=reloaded
