---

- hosts: mdk
  vars:
    letsencrypt_email: julien@palard.fr
  tasks:
    - name: Configure hostname
      hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Configure FQDN
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: "127.0.0.1 {{ inventory_hostname }} {{ inventory_hostname_short }} localhost"
        owner: root
        group: root
        mode: 0644

    - name: Setup nftables
      include_role: name=nftables
      tags: always
      vars:
        nftables_conf: |
            #!/usr/sbin/nft -f

            flush ruleset

            table inet filter {
                chain input {
                    type filter hook input priority 0;
                    iif lo accept
                    ct state established,related accept
                    tcp dport { ssh, http, https, 5201 } ct state new accept
                    ip protocol icmp icmp type { destination-unreachable, echo-reply, echo-request, source-quench, time-exceeded } accept
                    counter drop
                }
            }

    - name: Setup letsencrypt
      include_role: name=julienpalard.nginx_letsencrypt
      tags: always
      vars:
        letsencrypt_certificates:
          - [irc.mdk.fr]
          - [tuw.fr]

    - name: Exim4
      include_role: name=tschifftner.exim4_sendonly
