---

- hosts: mdk
  roles:
    - role: julienpalard.nginx_letsencrypt
      vars:
        certificates:
          - [mdk.fr, www.mdk.fr, julien.palard.fr, mandark.fr, palard.fr, sizeof.fr, www.mandark.fr, www.palard.fr, www.sizeof.fr]
          - [codeenseine.fr, www.codeenseine.fr]
          - [le-poitevin.fr, www.le-poitevin.fr]
          - [tuw.fr]
          - [wyz.fr, www.wyz.fr]
        letsencrypt_email: julien@palard.fr

    - role: static_website
      vars:
        uri: mdk.fr
        owner: mdk_fr
        path: /var/www/mdk.fr/
        public_deploy_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC/8I1ecV8EutLc+Qx6Q8b2RhzXMl9n23LznNlw+MQtM deploy'

    - role: static_website
      vars:
        uri: le-poitevin.fr
        owner: le_poitevin_fr
        path: /var/www/le-poitevin.fr/
        public_deploy_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBhFjd1nWN2N0xNm5N+sg9yMcb3sHrYWZ5vPdSUST0zn deploy'

    - role: static_website
      vars:
        uri: codeenseine.fr
        owner: codeenseine_fr
        path: /var/www/codeenseine.fr/
        public_deploy_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHVUrVDfDWwig4Vau0GJkvEpihMQXUhGVCBOQP6izGgx deploy'

    - role: weechat
      vars:
        version: 2.7
        owner: weechat
