---

- hosts: mdk
  roles:
    - role: nftables
      vars:
        nftables_conf: |
            #!/usr/sbin/nft -f

            flush ruleset

            table inet filter {
                chain input {
                    type filter hook input priority 0;
                    iif lo accept
                    ct state established,related accept
                    tcp dport { ssh, http, https } ct state new accept
                    counter drop
                }
            }

    - role: julienpalard.nginx_letsencrypt
      vars:
        certificates:
          - [mdk.fr, www.mdk.fr, julien.palard.fr, mandark.fr, palard.fr, sizeof.fr, www.mandark.fr, www.palard.fr, www.sizeof.fr]
          - [irc.mdk.fr]
          - [codeenseine.fr, www.codeenseine.fr]
          - [le-poitevin.fr, www.le-poitevin.fr]
          - [tuw.fr]
          - [wyz.fr, www.wyz.fr]
        letsencrypt_email: julien@palard.fr

    - role: static_website
      vars:
        uri: mdk.fr
        owner: mdk_fr
        path: /var/www/mdk.fr/
        public_deploy_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC/8I1ecV8EutLc+Qx6Q8b2RhzXMl9n23LznNlw+MQtM deploy'

    - role: static_website
      vars:
        uri: le-poitevin.fr
        owner: le_poitevin_fr
        path: /var/www/le-poitevin.fr/
        public_deploy_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBhFjd1nWN2N0xNm5N+sg9yMcb3sHrYWZ5vPdSUST0zn deploy'

    - role: static_website
      vars:
        uri: codeenseine.fr
        owner: codeenseine_fr
        path: /var/www/codeenseine.fr/
        public_deploy_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHVUrVDfDWwig4Vau0GJkvEpihMQXUhGVCBOQP6izGgx deploy'

    - role: weechat
      vars:
        version: 2.7
        owner: weechat

  tasks:
    - name: Setup Glowing Bear
      unarchive:
        src: https://github.com/glowing-bear/glowing-bear/archive/0.7.2.tar.gz
        remote_src: yes
        dest: "/usr/local/src/"

    - name: Configure irc.mdk.fr
      notify: reload nginx
      copy:
        dest: /etc/nginx/conf.d/irc.mdk.fr.conf
        content: |
          # Set connection header based on upgrade header
          map $http_upgrade $connection_upgrade {
              default upgrade;
              '' close;
          }

          server
          {
              listen 443 ssl;
              include snippets/letsencrypt-irc.mdk.fr.conf;
              add_header Content-Security-Policy "default-src 'self'; img-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; object-src 'none'; frame-src 'none'; font-src cdnjs.cloudflare.com;";
              add_header X-Frame-Options DENY;
              server_name irc.mdk.fr;

              location /
              {
                  root /usr/local/src/glowing-bear-0.7.2/;
                  index index.html;
              }

              location /weechat
              {
                  proxy_pass http://127.0.0.1:9000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection $connection_upgrade;
                  proxy_read_timeout 4h;
              }
          }

  handlers:
   - name: reload nginx
     service: name=nginx state=reloaded
