---

- hosts: mdk
  tasks:
    - name: Install rss2email
      apt: name=rss2email state=present

    - name: rss2email cron
      cron:
        user: mdk
        name: "rss2email"
        minute: "0"
        hour: "6,18"
        job: "/usr/bin/r2e run"

    - name: Configure rss2email
      copy:
        dest: /home/mdk/.config/rss2email.cfg
        owner: mdk
        group: mdk
        mode: 0644
        content: |
          [DEFAULT]
          from = user@rss2email.invalid
          use-8bit = False
          force-from = False
          use-publisher-email = False
          name-format = {feed-title}: {author}
          to = julien@palard.fr
          proxy =
          feed-timeout = 60
          active = True
          digest = False
          date-header = False
          date-header-order = modified, issued, created, expired
          bonus-header =
          trust-guid = True
          trust-link = False
          encodings = US-ASCII, ISO-8859-1, UTF-8, BIG5, ISO-2022-JP
          post-process =
          digest-post-process =
          html-mail = False
          use-css = False
          css = h1 {
          	font: 18pt Georgia, "Times New Roman";
          	}
          	body {
          	font: 12pt Arial;
          	}
          	a:link {
          	font: 12pt Arial;
          	font-weight: bold;
          	color: #0000cc;
          	}
          	blockquote {
          	font-family: monospace;
          	}
          	.header {
          	background: #e0ecff;
          	border-bottom: solid 4px #c3d9ff;
          	padding: 5px;
          	margin-top: 0px;
          	color: red;
          	}
          	.header a {
          	font-size: 20px;
          	text-decoration: none;
          	}
          	.footer {
          	background: #c3d9ff;
          	border-top: solid 4px #c3d9ff;
          	padding: 5px;
          	margin-bottom: 0px;
          	}
          	border: solid 4px #c3d9ff;
          	}
          	margin-left: 5px;
          	margin-right: 5px;
          	}
          unicode-snob = False
          links-after-each-paragraph = False
          body-width = 0
          email-protocol = sendmail
          sendmail = /usr/sbin/sendmail
          smtp-auth = False
          smtp-username = username
          smtp-password = password
          smtp-server = smtp.yourisp.net:25
          smtp-ssl = False
          smtp-ssl-protocol = TLSv1
          imap-auth = False
          imap-username = username
          imap-password = password
          imap-server = imap.yourisp.net
          imap-port = 143
          imap-ssl = False
          imap-mailbox = INBOX
          verbose = warning

          [feed.Agarri-Sécurité-informatique-offensive]
          url = http://www.agarri.fr/blog/rss.xml

          [feed.Daily-Security]
          url = https://www.dailysecurity.fr/feed/index.xhtml

          [feed.Framablog]
          url = https://framablog.org/feed/

          [feed.hackndo]
          url = http://beta.hackndo.com/feed.xml

          [feed.Hurricane-Labs]
          url = https://www.hurricanelabs.com/feed.rss

          [feed.Incidents-du-réseau-Framasoft]
          url = https://status.framasoft.org/atom

          [feed.LWN.net]
          url = https://lwn.net/headlines/newrss

          [feed.Segmentation-fault]
          url = http://www.segmentationfault.fr/feed/

          [feed.SSTIC---Blog]
          url = https://blog.sstic.org/index.xml

          [feed.top-scoring-links-cybersecurity]
          url = https://www.reddit.com/r/cybersecurity/top/.rss?t=month

          [feed.top-scoring-links-hacking]
          url = https://www.reddit.com/r/hacking/top/.rss?t=month

          [feed.top-scoring-links-netsec]
          url = https://www.reddit.com/r/netsec/top/.rss?t=month

          [feed.top-scoring-links-security]
          url = https://www.reddit.com/r/security/top/.rss?t=month

          [feed.top-scoring-links-securityCTF]
          url = https://www.reddit.com/r/securityCTF/top/.rss?t=month
