---

- import_playbook: cert_watch.yml
- import_playbook: common.yml
- import_playbook: pasteque.yml
- import_playbook: static_websites.yml
- import_playbook: weechat.yml
- import_playbook: rss2email.yml
