---

- name: Configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/{{ uri }}.conf
  notify: reload nginx

- name: WWW directory
  file:
    path: "{{ path }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ owner }}"
    mode: 0755
